build: update qrcode to 8.2
The AppImage build failed with:

```
ValueError: ('Invalid group name', 'console-scripts')
```

caused by qrcode, see:

https://github.com/lincolnloop/python-qrcode/pull/229